# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/twotwo',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/twotwo',
                'lib_path': 'twotwo'},
  'syms': {'twotwo.core': {'twotwo.core.foo': ('core.html#foo', 'twotwo/core.py')}}}
